CREATE TABLE VOLCANO_ERUPTION (Year INT,Month INT,Day INT,TSU VARCHAR,EQ VARCHAR,Name VARCHAR,Location VARCHAR,Country VARCHAR,Latitude FLOAT8,Longitude FLOAT8,Elevation INT,
Type VARCHAR,Status VARCHAR,Time VARCHAR,VEI INT ,Agent VARCHAR,DEATHS INT,DEATHS_DESCRIPTION INT,MISSING INT,MISSING_DESCRIPTION INT,INJURIES INT,
INJURIES_DESCRIPTION INT,DAMAGE_MILLIONS_DOLLARS FLOAT8,DAMAGE_DESCRIPTION INT,HOUSES_DESTROYED INT,HOUSES_DESTROYED_DESCRIPTION INT,
TOTAL_DEATHS INT,TOTAL_DEATHS_DESCRIPTION INT,TOTAL_MISSING INT,TOTAL_MISSING_DESCRIPTION INT,TOTAL_INJURIES INT,TOTAL_INJURIES_DESCRIPTION INT,
TOTAL_DAMAGE_MILLIONS_DOLLARS FLOAT8,TOTAL_DAMAGE_DESCRIPTION INT,TOTAL_HOUSES_DESTROYED INT,TOTAL_HOUSES_DESTROYED_DESCRIPTION INT);

COPY VOLCANO_ERUPTION from '../data/volerup.txt.tsv' with DELIMITER AS E'\t' NULL AS '';

CREATE TABLE TSUNAMI_EVENT(ID INT,YEAR INT,MONTH INT,DAY INT,HOUR INT,MINUTE INT,SECOND FLOAT8,EVENT_VALIDITY INT,CAUSE_CODE INT,FOCAL_DEPTH INT,PRIMARY_MAGNITUDE FLOAT8,
COUNTRY VARCHAR,STATE VARCHAR,LOCATION_NAME VARCHAR,LATITUDE FLOAT8,LONGITUDE FLOAT8,REGION_CODE INT,MAXIMUM_WATER_HEIGHT FLOAT8,ABE VARCHAR,IIDA FLOAT8,SOLOVIEV FLOAT8,
WARNING_STATUS INT,DEATHS INT,DEATHS_DESCRIPTION INT,MISSING INT,MISSING_DESCRIPTION INT,INJURIES INT,INJURIES_DESCRIPTION INT,DAMAGE_MILLIONS_DOLLARS FLOAT8,DAMAGE_DESCRIPTION INT,
HOUSES_DESTROYED INT,HOUSES_DESTROYED_DESCRIPTION INT,HOUSES_DAMAGED INT,HOUSES_DAMAGED_DESCRIPTION INT,TOTAL_DEATHS INT,TOTAL_DEATHS_DESCRIPTION INT,TOTAL_MISSING INT,TOTAL_MISSING_DESCRIPTION INT,
TOTAL_INJURIES INT,TOTAL_INJURIES_DESCRIPTION INT,TOTAL_DAMAGE_MILLIONS_DOLLARS FLOAT8,TOTAL_DAMAGE_DESCRIPTION INT,TOTAL_HOUSES_DESTROYED INT,TOTAL_HOUSES_DESTROYED_DESCRIPTION INT,
TOTAL_HOUSES_DAMAGED INT,TOTAL_HOUSES_DAMAGED_DESCRIPTION INT);

COPY TSUNAMI_EVENT from '../data/tsevent.txt.tsv' with DELIMITER AS E'\t' NULL AS '';

ALTER TABLE VOLCANO_ERUPTION
ADD COLUMN THE_GEOM GEOMETRY(POINT,4326);

UPDATE VOLCANO_ERUPTION
SET THE_GEOM = ST_SetSRID(
	ST_MakePoint(Longitude,Latitude), 4326
);

ALTER TABLE TSUNAMI_EVENT
ADD COLUMN THE_GEOM GEOMETRY(POINT,4326);

UPDATE TSUNAMI_EVENT
SET THE_GEOM = ST_SetSRID(
	ST_MakePoint(Longitude,Latitude), 4326
);

--SELECT * from TSUNAMI_EVENT;
--SELECT * from VOLCANO_ERUPTION;
--SELECT * FROM WORLD;


SELECT ID,ST_Buffer(ST_MakePoint(Longitude,Latitude)::geography, 160000) AS GEO,LOCATION || ', ' || COUNTRY AS LOCATION, DEATHS INTO VOLCANO_RESUMEN FROM VOLCANO_ERUPTION;

